/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_slmcontrol_slmAPI */

#ifndef _Included_com_slmcontrol_slmAPI
#define _Included_com_slmcontrol_slmAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_slmcontrol_slmAPI
 * Method:    sendData
 * Signature: ([DC)V
 */
JNIEXPORT void JNICALL Java_com_slmcontrol_slmAPI_sendData
  (JNIEnv *, jobject, jdoubleArray, jchar);

#ifdef __cplusplus
}
#endif
#endif
